export const FAVORITE_LOADING = "FAVORITE_LOADING";
export const FAVORITE_FAILURE = "FAVORITE_FAILURE";
export const FETCH_FAVORITE = "FETCH_FAVORITE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
