export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_FAILURE = "ORDER_FAILURE";
export const FETCH_ORDER = "FETCH_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const ERROR = "ERROR";
export const CANCEL_ORDER_SUCCESSFUL = "CANCEL_ORDER_SUCCESSFUL";

